### ISSUE TITLE
Install debian installer with packages

### ISSUE THREAD

**Issue by rezib** [edf-hpc/puppet-hpc#102]
Currently, the netboot.tar.gz blob is stored in internal repository. How the archive is supposed to land here is not documented. It should be installed and distributed like all other software, ie. with distribution packages.

**Comment by rezib** [comment]
Note we can actually rely on an existing package for this purpose:
https://packages.debian.org/jessie/debian-installer-8-netboot-amd64

**Comment by hmlth** [comment]
https://github.com/scibian/scibian-hpc-install-guide/commit/a2669533570b15baecb569d932cceed3977c7231#diff-a8c27a8e27e83467e9a1b9e4f6ba3737
