### ISSUE TITLE
hpc-config-apply should be verbose by default when stdout is TTY

### ISSUE THREAD

**Issue by rezib** [edf-hpc/puppet-hpc#112]
Currently, hpc-config-apply redirects all output to syslog by default. The `-v` flag must be given to get all outputs on the user TTY (stdout/stderr). As users generally want the output and syslog is used in corner cases (hpc-config-apply boot time service), the default should be the verbose mode. A `--syslog` parameter (or similar) should be added for the service.

**Comment by hmlth** [comment]
This behavior was a copy of the old init.calibre behavior. The default could change. I think there is a missing verbosity level with only errors and a one line summary at the end that could be suitable for a launch by clustershell.

**Comment by mehdid** [comment]
IMO, the best solution is to make the script detect if stdout is a TTY. In such cases, hpc-config-apply would be verbose by default. When stdout is not a TTY, hpc-config-apply uses syslog or other appropriate.

Thomas's proposal is another feature, and which I also think would be very welcome. I suggest to make another ticket for it though.

**Comment by rezib** [comment]
> IMO,  the best solution is to make the script detect if stdout is a TTY. In such cases, hpc-config-apply would be verbose by default. When stdout is not a TTY, hpc-config-apply uses syslog or other appropriate.

Yes, i agree.

**Comment by mehdid** [comment]
This issue was moved to edf-hpc/hpc-config#3
