### ISSUE TITLE
Keepalive package hasn't ipvsadm in dependancies on stretch

### ISSUE THREAD

**Issue by boinamib** [edf-hpc/puppet-hpc#132]
In contrary to debian jessie the version of keepalived package in stretch  hasn't ipvsadm in dependancies.

**Comment by fmdm** [comment]
If we still want this software installed with keepalived, we need to manage it in the keepalived module or in a new module.

**Comment by mehdid** [comment]
ipvsadm is brought by the puppet module now (See https://github.com/scibian/puppet-module-arioch-keepalived/commit/dcd1b95ff1470e4483a57db2f0d654b3db014129). This ticket can be closed.
