### ISSUE TITLE
Munge module not installable with default values

### ISSUE THREAD

**Issue by fmdm** [edf-hpc/puppet-hpc#25]
This commit broke munge module when used with default values : 
https://github.com/edf-hpc/puppet-hpc/commit/af18e000bb3fcf4dee74c054d0279097308ae519

We need to support url and puppet file declaration in this function.

**Comment by hmlth** [comment]
Fixed by :
https://github.com/edf-hpc/puppet-hpc/commit/ad6561359bba0b2c7a5a7122a637496ee1a93534#diff-0cc1f9fd24cbbb4cfb923eb2e3fdc58a
https://github.com/edf-hpc/puppet-hpc/commit/6b3cf2e75bc3fbd09cf4ab37a356783f16711f87#diff-0cc1f9fd24cbbb4cfb923eb2e3fdc58a
