### ISSUE TITLE
mod:pam:slurm modifies a file in /usr/share/pam-config

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/puppet-hpc#40]
This is not authorized by pam-auth-update documentation (https://wiki.ubuntu.com/PAMConfigFrameworkSpec):

> Package config declarations are shipped in the packages in /usr/share/pam-configs, and are not user-editable.

This can be solved by:
 
* modifying files in `/etc/pam.d` directly (like classes access and limits)
* Waiting for the packaging issue https://github.com/edf-hpc/slurm-llnl/issues/2 to be fixed

**Comment by rezib** [comment]
Fixed with dae6f04.
