### ISSUE TITLE
Slurmdbd backup script should be provided by package

### ISSUE THREAD

**Issue by rezib** [edf-hpc/puppet-hpc#60]
The slurm module provides a slurmdbd backup script. It should be provided a package like the setup script, typically within the [misc package](https://github.com/edf-hpc/slurm-llnl-misc-plugins).

**Comment by hmlth** [comment]
Fixed by 
https://github.com/edf-hpc/slurm-llnl-misc-plugins/commit/2fe5288d579c7f2e0e05957c0bb75d384c51f3ef

https://github.com/edf-hpc/puppet-hpc/commit/6bfe3ee3336d25d34339782db33a98862aa393b3
