### ISSUE TITLE
Configure network interfaces in static mode on debian

### ISSUE THREAD

**Issue by rezib** [edf-hpc/puppet-hpc#70]
Currently, the network interfaces are configured on Debian in manual mode:

https://github.com/edf-hpc/puppet-hpc/blob/b9bd74bf1cf4616928d6e6bd13e124a47804830a/puppet-config/modules/network/templates/interfaces.erb#L70

This causes some issues, notably with services depending on NFS depending on Ethernet bonding. We have to think going back to standard static mode.

**Comment by mehdid** [comment]
For reference, can you explain more in details the issues caused by the manual mode? (and why it works better with static mode)

**Comment by rezib** [comment]
We have an issue where the `network-online.target` is reached before the network is actually online especially when bonding and bridges are setup in our `/etc/network/interfaces` files. This implies failed NFS mounts (requiring systematically async retries) and failed services start (ex: tftp-hpa) even when waiting for `remote-fs.target`.

I _think_ using static mode in `/etc/network/interfaces` might help to have proper integration between `ifupdown` and `network-online.target`.
