### ISSUE TITLE
"local_domain" and "domain" could be merged

### ISSUE THREAD

**Issue by fmdm** [edf-hpc/puppet-hpc#78]
The distinction between "local_domain" and "domain" (which is the domain name outside of the cluster) is problematic as it implies use of two different domains in machines's fqdn (macines with acces to wan have a different domain than machines with local network only).

Maybe we can have only one domain matching the external domain, with an internal DNS server authoritative on this domain.

**Comment by mehdid** [comment]
I guess this is done now in https://github.com/edf-hpc/puppet-hpc/commit/8d9fc7f8d55670d19fe67c72ff28977804350be2 or do we have more tests to do for this one?
