### ISSUE TITLE
Refactor network module: Be consistent between ib and opa

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/puppet-hpc#95]
IB and OPA do the same thing differently for no good reasons.

For example, the ipoib is activated by an option in the openib service in IB and through systemd module load in OPA. Solution is probably to use the RDMA (or openib) service in the same way on the two stacks.

**Comment by rezib** [comment]
It seems there is no common way to load ipoib module between Mellanox OFED stack and Intel OPA and conform to their respective installation guides (and therefore their technical support). The solution we are currently using for the 2 stacks are rather conform to these guides. Now that Mellanox OFED Linux stack and Intel OPA node stack are managed by two different modules (out of network module), the cosmetic issue is not that obvious anymore.

For these reasons, I propose to **not fix** this issue.

**Comment by rezib** [comment]
After discussion, we have validated to not fix it.
